### ISSUE TITLE
Crash in getAvailableSlotsHost

### ISSUE THREAD

**Issue by Flamefire** [ComputationalRadiationPhysics/mallocMC#106]
Since the change in 229c8916afb82594a060e1711d13034d52840536 the initHeap() function crashes the program without any error in the kernel call to ScatterKernelDetail::getAvailableSlotsKernel<<<64,256>>>(heap, slotSize, d_slots) (Scatter_impl.hpp:941)

CUDA 7.5, gcc 4.8.2, C++11 mode in 3rd party project. Reverting the change to `mallocMC_hostclass.hpp` resolves that.

**Comment by Flamefire** [comment]
I found a difference caused by the commit that can be the problem: Before the commit, `getAvailableSlotsHost` is called in `initHeap`. After the commit, it calls into `GetAvailableSlotsIfAvail::getAvailableSlots` which has an `ifdef` for calling either the host or accelerator version. So when `__CUDA_ARCH__` is defined, `getAvailableSlotsHost` is never instantiated.

**Comment by Flamefire** [comment]
I reproduced the issue with the following example code: https://gist.github.com/Flamefire/bedfd966a4fd49d02ee3

**Comment by slizzered** [comment]
Could you try compiling with `nvcc -dc `?
(in CMake: `set(CUDA_SEPARABLE_COMPILATION ON)`)

**Comment by Flamefire** [comment]
No change for the minimal example. @psychocoderHPC mentioned that using the macro in this way is forbidden/unsupported according to the cuda programming guide.

**Comment by psychocoderHPC** [comment]
The problem is that kernel calls inside `__CUDA_ARCH__` are not supported by nvcc. 
You can find this in the programming guide ( a link is coming )

**Comment by Flamefire** [comment]
Using the macro as a template param does also not solve the problem. Only solution I see so far is actually calling the host function like it was done before.

**Comment by psychocoderHPC** [comment]
We should build to explicit methods, one for the host and one for the device. 
Offline discussed with @Flamefire  and we think this is the only clean solution.

**Comment by slizzered** [comment]
Ok thanks for digging into this, I didn't know that this behaviour wasn't officially supported. Two explicit methods sounds good as well. It is certainly the more robust solution.
