### ISSUE TITLE
boost dependency: grep-able

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/mallocMC#114]
@psychocoderHPC just realized the following:

it would be quite neat if we could replace the hard-coded boost min-version in [FindmallocMC.cmake](https://github.com/ComputationalRadiationPhysics/cmake-modules/blob/536745ec8bba550d413e6477310036d99674d6b4/FindmallocMC.cmake#L65) by the following logic **inside `FindmallocMC.cmake`**:
- find mallocMC
- parse min version (to CMake var `mallocMC_BOOST_MIN_VERSION`)
- `find_package(Boost mallocMC_BOOST_MIN_VERSION REQUIRED)`

This PR is to remind that we need, e.g., close to `version.h` or `CMakeList.txt` a define that can be queried.

**Comment by ax3l** [comment]
maybe this can also be solved with cmake config files (?)

**Comment by ax3l** [comment]
can be moved to 2.3+

**Comment by psychocoderHPC** [comment]
the boost depedency is removed with #169 so I will close this issue

**Comment by ax3l** [comment]
nice, for the record, the right way to do this these days would have been with the `find_dependency(...)` macro:
https://github.com/openPMD/openPMD-api/blob/0.11.1-alpha/openPMDConfig.cmake.in#L26
