### ISSUE TITLE
Hardcoded flag for compute capability 2.0

### ISSUE THREAD

**Issue by sbastrakov** [ComputationalRadiationPhysics/mallocMC#162]
[This line](https://github.com/ComputationalRadiationPhysics/mallocMC/blob/e2533d14101c9fa7af3d11b9d02277591e06d8e4/CMakeLists.txt#L25) has a hardcoded flag for compute capability 2.0, which is not supported since CUDA 9. So examples do not compile with the compiler stack used by Alpaka and PIConGPU.
The cmake file generally has room for improvement, but this is the most immediate issue.

**Comment by ax3l** [comment]
Little regression noted in https://github.com/ComputationalRadiationPhysics/mallocMC/pull/164#discussion_r328350556

Re-opening to keep track of it, so it does not get lost.

**Comment by psychocoderHPC** [comment]
Thanks for re-open it. The ddev branch is the default branch, therefore, this issue gets auto closed.

**Comment by sbastrakov** [comment]
@ax3l thanks, will do. However, not sure how is that a regression.

**Comment by ax3l** [comment]
Thanks for fixing!
