### ISSUE TITLE
runs out of memory although memory is still available

### ISSUE THREAD

**Issue by slizzered** [ComputationalRadiationPhysics/mallocMC#69]
When using a configuration with hierarchies, the code from ScatterAlloc can produce a bug where some threads can not find any free memory although there is enough available.

**tested configuration:**  
 - pagesize = 2MiB
 - size of allocated chunks = 8KiB (precise values do not matter, as long as there are more than 32 chunks in a page, so the hierarchy-algorithm is used).
 - CUDA 6.5
- Kepler K20m (sm_35)

**possible reason:**
ScatterAlloc was written for Fermi (sm_20) and with an older version of the CUDA compiler. On newer hardware/compilers, there might be a problem with the caches when reading/writing bitmasks concurrently on different blocks.

The bitmask in the PageTable as well as the on-page bitmasks are written with atomic operations, but this does not guarantee that all threads always load the correct values (i.e. the L1 caches might still hold old values that get read). 

**possible solution:**  
- try to disable all caches / run on older hardware with older compiler and see if bug still occurs
- use some synchronization method (`threadfence_block()` or `threadfence()`)

**Comment by slizzered** [comment]
I can no longer reproduce the bug, might have been entirely solved through #70.
If it occurs again, feel free to re-open.

**Comment by ax3l** [comment]
sounds good!

you could try to fuzzy-test it by filling the full memory with random values, deallocating it and then starting your test with your mem controller (still in the same cuda context).
