### ISSUE TITLE
hard coded heap size

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/mallocMC#78]
I found a hard coded heap size of `8MiB` inside the code.

https://github.com/ComputationalRadiationPhysics/mallocMC/blob/dev/src/include/mallocMC/mallocMC_overwrites.hpp#L50

Is there any reason for this magic number?

**Comment by slizzered** [comment]
ScatterAlloc used these `8MB` as a default, so it was left unchanged for compatibility reasons (the init-function still behaves the same as the reference implementation of ScatterAlloc when called with no parameters).

https://github.com/ComputationalRadiationPhysics/mallocMC/blob/tugraz/tools/heap_impl.cuh#L41

**Comment by psychocoderHPC** [comment]
Ahh OK thanks for the fast response.

**Comment by ax3l** [comment]
still, don't we want to expose that parameter for future use?

**Comment by slizzered** [comment]
It is already a parameter for a the function and can be directly set by the user. The `8MB` are only a default value for the parameter, in case the user decides not to set any heap size.

**Comment by ax3l** [comment]
:+1: all right
