### ISSUE TITLE
Sort: New 2.2.0 release and upcoming to 2.3.0

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/mallocMC#94]
@slizzered I was wondering if we want to put more of the open issues to `2.2.0` or if you would like to create a new milestone and move some of them there (maybe with a more distinct headline than "New features" and "More New Features" ^^).

The idea behind that: we are currently running on mallocMC's `dev` in PIConGPU's `dev` which makes the version not 100% correct (a "real" 2.1.0 would not work but the `dev`/post-2.1.0 mallocMC we ship with PIConGPU works). I would rather like to ship a new stable release of mallocMC to avoid problems with an upcoming stable release of PIConGPU.

**Comment by ax3l** [comment]
@slizzered pls create a new milestone, I would like to draft a release soon :)

**Comment by slizzered** [comment]
For now I moved almost all open issues to "Future Ideas", so we might just finish the **2.2.0crp** Milestone and create a stable release from that.

**Comment by ax3l** [comment]
great!

**Comment by ax3l** [comment]
@slizzered are we able to draft a release from `dev`?

**Comment by slizzered** [comment]
I still have to fix #98, but that can be done in a few minutes. Afterwards we should be good to go.
