### ISSUE TITLE
rename `uint` varible

### ISSUE THREAD

**Issue by psychocoderHPC** [ComputationalRadiationPhysics/mallocMC#98]
Should we rename the type [`uint32_richtig_huebsch`](https://github.com/ComputationalRadiationPhysics/mallocMC/blob/b5737f708102e417698f2ed198f280ab66ac71ab/src/include/mallocMC/mallocMC_utils.hpp#L115)?

**Comment by ax3l** [comment]
hm, I can barely imagine a better name but I agree if you insist ;)

**Comment by bussmann** [comment]
+1
